### ISSUE TITLE
Feature request | Show previously selected location

### ISSUE THREAD

**Issue by moriswala** [blackmann/locationpicker#10]
Same picker could be reused to show selected location to the user with little enhancement. Can we have something like 
```
**LatLng location = LatLng(12.000000, 11.000000);**
result = await Navigator.of(context).push(MaterialPageRoute(
          builder: (context) =>
              PlacePicker(Constants.GOOGLE_API_KEY, **location**)));
```

**Comment by blackmann** [comment]
This is a great idea @moriswala . Will make that change today.

**Comment by blackmann** [comment]
@moriswala this issue has been addressed.

Pass in an optional `displayLocation` to `PlacePicker` constructor to enable this feature.
