### ISSUE TITLE
Issues when using the dark theme.

### ISSUE THREAD

**Issue by dariotrombello** [blackmann/locationpicker#15]
![Screenshot_20191208-171837](https://user-images.githubusercontent.com/24731809/70392301-01fd4b80-19df-11ea-96ad-ac2d8a5973ea.jpg)

When using dark theme the text is not visible anymore.

Code to reproduce this:
```dart
    return MaterialApp(
      title: 'Google Maps',
      darkTheme: ThemeData.dark(),
      theme: ThemeData.dark(),
      home: Home(),
    );
```

**Comment by blackmann** [comment]
@dariotrombello thanks for raising this issue. I'll try  to resolve this during this week.

**Comment by dariotrombello** [comment]
Thank you very much!

**Comment by blackmann** [comment]
@dariotrombello Dark theming is enabled. Enjoy!!
