### ISSUE TITLE
LocationResult - Types/Icon request

### ISSUE THREAD

**Issue by bhutanigautam** [blackmann/locationpicker#18]
Firstly, thank you for building this. Post the deprecation of the Google Place package, I was planning to build my own and after much search and research, I found your package.

I appreciate how you are using the web-service result to render the nearby places; would it be possible for you to expose the icon and types properties in `LocationResult` for the consuming apps?

**Comment by blackmann** [comment]
Yes it would be possible to expose those properties. But the type and icon data can only be retrieved when the selected location is listed inside the nearby places.

If you'd like to get these extra attributes, you can do that with the current `LocationResult` returned and Places API. Have a look here on how to do that: https://developers.google.com/places/web-service/details
