### ISSUE TITLE
Location result is coming null

### ISSUE THREAD

**Issue by nvamsi214** [blackmann/locationpicker#24]
Hello,
I have been using your package for a while now. It was working fine till now. But from last few days i'm not getting the place result. Its giving me null & i'm not getting any exception too. Place picker is showing the current location and nearby places correctly, but not the selected location details. Help me to figure out what could be the issue.

Below is the attachment where you can see that the place details is showing as Unnamed location.
![error](https://user-images.githubusercontent.com/33240181/77039114-42effd80-69db-11ea-91fa-1485777d7493.jpeg)

**Comment by blackmann** [comment]
Does search work? @nvamsi214

**Comment by nvamsi214** [comment]
yes, search will give the search results, but once i select a location place result will be null.

**Comment by shuaibbapputty** [comment]
> Hello,
> I have been using your package for a while now. It was working fine till now. But from last few days i'm not getting the place result. Its giving me null & i'm not getting any exception too. Place picker is showing the current location and nearby places correctly, but not the selected location details. Help me to figure out what could be the issue.
> 
> Below is the attachment where you can see that the place details is showing as Unnamed location.
> ![error](https://user-images.githubusercontent.com/33240181/77039114-42effd80-69db-11ea-91fa-1485777d7493.jpeg)

Me too.

for me search and nearby also doesn't works..
Can you please note out the changes you made.

**Comment by blackmann** [comment]
@nvamsi214 can I have a look at the code you use to launch the place picker?

**Comment by AbedRabaia** [comment]
@blackmann Am having the same issue

**Comment by muhamedfayed** [comment]
Same issue

**Comment by sehejjain** [comment]
Same Issue.
UPDATE: RESOLVED

In addition to enabling Places API, Maps SDK for Android and Maps SDK for iOS for the API key, it should needs the Geocoding API.
I hope the documentation will be updated.
Everything works now.

**Comment by abiudorina** [comment]
Thank you so much for this. I had the same problem and this worked. Please update the documentation @blackmann . 

> Same Issue.
> UPDATE: RESOLVED
> 
> In addition to enabling Places API, Maps SDK for Android and Maps SDK for iOS for the API key, it should needs the Geocoding API.
> I hope the documentation will be updated.
> Everything works now.

**Comment by WaheedHussainHaans** [comment]
@blackmann I have geocoding enabled as well but its not working for me the result is always null on android iOS it works
