### ISSUE TITLE
Crash on 2nd open

### ISSUE THREAD

**Issue by festelo** [blackmann/locationpicker#3]
![image](https://user-images.githubusercontent.com/20724864/62462409-05ae6680-b790-11e9-861d-a24886321257.png)
```
    final result = await Navigator.of(context).push(MaterialPageRoute(
      builder: (context) =>
        Theme(
          data: Theme.of(context).copyWith(
            accentColor: Colors.black
          ),
          child: PlacePicker(Api.googleKey),
        ) 
      )
    );
```

**Comment by blackmann** [comment]
@festelo did you finish up the android setup??

Also can you elaborate on your issue?? What does 2nd open mean; place picker screen open or the whole app open??

**Comment by festelo** [comment]
>did you finish up the android setup??
1. ACCESS_FINE_LOCATION setted
2. com.google.android.geo.API_KEY setted
3. gradle.properties updated


>What does 2nd open mean; place picker screen open or the whole app open??  

The code i sent executes when button has been pressed. On 1st button press PlacePicker successfully opens, but when i close PlacePicker and press the button again - the app crashes.

I found another library and maybe it's fork of yours, but this library works fine.
https://github.com/humazed/google_map_location_picker

I'll try to make codesample tomorrow

**Comment by blackmann** [comment]
It'll be great if i saw the code sample so I can help.

**Comment by blackmann** [comment]
Closing this issue for the sake of inactivity.
