### ISSUE TITLE
How Do I set Dark mode?

### ISSUE THREAD

**Issue by amirhabibz** [blackmann/locationpicker#31]
I'm not sure How to set the dark mode. I don't see any parameters to set this in PlacePicker().

**Comment by AxeemHaider** [comment]
Exactly, there is no documentation how you can set Dark mode. 
@amirhabibz you find any solution how to set dark mode ?

**Comment by amirhabibz** [comment]
@AxeemHaider I didn't figure it out. I set my phone to dark mode as well and it didn't change. I think we have to set a dark mode theme manually ourselves in main.dart.

**Comment by AxeemHaider** [comment]
@amirhabibz is this package is working for you because this package is not working for me whenever I select any place it give range error. 
see issue #32 someone send a pull request to fix this but owner is not merging it I don't know why. I think this package is no longer maintain.

**Comment by blackmann** [comment]
@amirhabibz sorry for the late reply. You're right, you have to set a dark theme globally in your app (dart code) for it to work.
