### ISSUE TITLE
RangeError Invalid value not in range 0..5, inclusive 7

### ISSUE THREAD

**Issue by AxeemHaider** [blackmann/locationpicker#32]
I'm using `place_picker 0.9.14` After installing and configure everything enabling APIs which are mention I try to run this package.
Whenever I select any place it give an error.

> RangeError (index) Invalid value not in range 0..5, inclusive 7

Billing is also enable in my account.

I see there is a pull request where I think this problem is saved but don't know why owner of this is not merging it.

**Comment by nombrekeff** [comment]
I'm also facing this issue and can't select places. It lists the places in the search box but does not select it.

Any idea what could be causing this? 

I have a version of the APP in production with same token and it works perfectly. But new build fails to work.

**Comment by blackmann** [comment]
@AxeemHaider PR has been merged for a long while now. Sorry for not getting back sooner.
