### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by daverupp** [blackmann/locationpicker#37]
@blackmann thx for the super work
One question. I see the english string hard coded in the code. Is it possible to expose these values to the constructor of PlacePicker so I can actually localize the widget? 

would be super cool if you could do that... Would love to use this super nice widget.

**Comment by blackmann** [comment]
Hi @daverupp thank you 😊, I'm currently busy with lots of stuff and I can't assure to make this a priority right now. However, if you could please present an MR with the solution, I will be happy to merge it.

**Comment by daverupp** [comment]
hmm wondering how to do :) 

I tried to create a branch of the master, but when I want to commit the branch, I am not allowed to ... any idea?
Do I have to update the master directly and do a pull request? Not used to do pull-requests :) sorry

**Comment by daverupp** [comment]
I think I have a solution ready :D

**Comment by daverupp** [comment]
@blackmann can you add me as contributer, so I can contribute? :) 
would love to share the code...

**Comment by blackmann** [comment]
@daverupp great. To contribute, please fork this repo and clone it. Then do `git checkout -b localization`. In this branch, make your edits. When you're done push to your origin.

Then head over to this repo and create a new pull request. If this is too much theory (it's pretty straightforward though) join my [Discord Server](https://discord.gg/5CDnysz) and I can assist you.

I'm itching to have your contribution haha
