### ISSUE TITLE
LocationResult always return a null result

### ISSUE THREAD

**Issue by UnluckyY1** [blackmann/locationpicker#42]
LocationResult always return a null result 
```
I/flutter (23296): result
I/flutter (23296): null
```

**Comment by blackmann** [comment]
Do you have all the required APIs enabled for your key? As well as billing? 

Please reference the `README` to see if you haven't missed a requirement

**Comment by panchalAlpit** [comment]
@blackmann Please suggest how many APIs are required. please give the required APIs name.
