### ISSUE TITLE
"http" Dependency creating conflicts

### ISSUE THREAD

**Issue by coretea** [blackmann/locationpicker#43]
Good morning,
Your Place Picker Migrarted package in "pub.dev" is based on HTTP package on version "0.12.2".
While the other new packages from Google, Firebase, and Flutter are using the new API with the HTTP version "0.13".
This creates a conflict that cannot be overridden because of the API change.

I'd be glad if you could help to migrate it to the new HTTP package.
Omer

**Comment by blackmann** [comment]
This has been resolved. Thanks for pointing out. And I'm sorry for the delay.
