### ISSUE TITLE
google_maps_flutter dependency issue

### ISSUE THREAD

**Issue by osama-157** [blackmann/locationpicker#45]
Good morning,
Your Place Picker Migrarted package in "pub.dev" is based on google_maps_flutter package on version "^1.0.5".
This creates a conflict that cannot be overridden because of the API change.

`Because place_picker >=0.9.16 depends on google_maps_flutter ^1.0.5 and geenacom depends on google_maps_flutter ^2.0.1, place_picker >=0.9.16 is forbidden.
So, because geenacom depends on place_picker ^0.9.18, version solving failed.
pub get failed (1; So, because geenacom depends on place_picker ^0.9.18, version solving failed.)
Process finished with exit code 1`

I'd be glad if you could help to migrate it to the new google_maps_flutter package.

**Comment by blackmann** [comment]
Resolved in `0.9.18-nullsafety`
