### ISSUE TITLE
Null Safe version

### ISSUE THREAD

**Issue by excode** [blackmann/locationpicker#47]
Please let release  the null safety  version.  We are stuck or give us some clue of fix it from our end. 

Thank you

**Comment by blackmann** [comment]
Resolved in `0.9.18-nullsafety`

**Comment by excode** [comment]
thanks bro

**Comment by excode** [comment]
Compiler still shows it as non null safety 

Is there any workaround 

Package Name  Current  Upgradable  Resolvable  Latest   

direct dependencies:
place_picker  ✗0.9.18  ✗0.9.18     ✗0.9.18     ✗0.9.18

**Comment by blackmann** [comment]
Please use version `0.9.18-nullsafety`

**Comment by excode** [comment]
![image](https://user-images.githubusercontent.com/4152357/111999184-f0de3c80-8b46-11eb-918e-3dd6af27dd30.png)


Already added 0.9.18-nullsafety  but when I am trying to run flutter it throws 0.9.18 is not null safty

**Comment by blackmann** [comment]
Please use `0.9.19-nullsafety` instead and let me know what happens. I just publish an update

**Comment by excode** [comment]
Thumbs up !!! now it working ...  Thank you
