### ISSUE TITLE
Build crashes with Flutter 2.6

### ISSUE THREAD

**Issue by kbayegan** [blackmann/locationpicker#62]
Here are the errors. They happen running only the example and noting else:

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    2 warnings generated.
    /Users/kamran/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/ios/Classes/LocationPlugin.m:134:13: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from /Users/kamran/Dropbox/Flutter/p_picker/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/kamran/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/ios/Classes/LocationPlugin.m:134:48: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from /Users/kamran/Dropbox/Flutter/p_picker/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    ../../../flutter/.pub-cache/hosted/pub.dartlang.org/place_picker-0.9.18/lib/widgets/rich_suggestion.dart:35:89: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
     - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
          TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.body1.color)),
                                                                                          ^^^^^
    ../../../flutter/.pub-cache/hosted/pub.dartlang.org/place_picker-0.9.18/lib/widgets/search_input.dart:60:65: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
     - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
              Icon(Icons.search, color: Theme.of(context).textTheme.body1.color),
                                                                    ^^^^^
    Failed to package /Users/kamran/Dropbox/Flutter/p_picker.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    note: Removed stale file '/Users/kamran/Library/Developer/Xcode/DerivedData/Runner-duplwfdeendbofblbjbckmbcyqsf/Build/Products/Debug-iphonesimulator/Runner.app'

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by nikitabuida** [comment]
Here's a temporary solution:
https://github.com/blackmann/locationpicker/issues/57#issuecomment-916621500

**Comment by blackmann** [comment]
Fixed in #67
