### ISSUE TITLE
after upgrade flutter 2.2.3 to 2.5.0 i got this error

### ISSUE THREAD

**Issue by Sreejith93** [blackmann/locationpicker#63]
/E:/Andriod/flutter/.pub-cache/hosted/pub.dartlang.org/place_picker-0.9.19-nullsafety/lib/widgets/rich_suggestion.dart:35:89: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/Andriod/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
      TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.body1.color)),
                                                                                        ^^^^^
/E:/Andriod/flutter/.pub-cache/hosted/pub.dartlang.org/place_picker-0.9.19-nullsafety/lib/widgets/search_input.dart:60:65: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/Andriod/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
          Icon(Icons.search, color: Theme.of(context).textTheme.body1.color),
                                                                ^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Andriod\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Andriod\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s

**Comment by lucasjinreal** [comment]
@blackmann  same error here

**Comment by Sreejith93** [comment]
any solution please

**Comment by RockNav24** [comment]
Same error

**Comment by alishe79** [comment]
same error here

**Comment by RoRoStudio** [comment]
Edit the lines in the dart package like below and it will work. Of course the author should do this, but you can edit it yourself as well :) 

**rich_suggestion.dart** 
Original: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.**body1!**.color)),

New: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.**bodyText1!**.color)),

**search_input.dart**
Original: Icon(Icons.search, color: Theme.of(context).textTheme.**body1!**.color),

New: Icon(Icons.search, color: Theme.of(context).textTheme.**bodyText1!**.color),

![image](https://user-images.githubusercontent.com/78321675/140312056-4cc7323c-c659-4ca9-8114-97d204f44ce2.png)

**Comment by zotovy** [comment]
same error

**Comment by negiot** [comment]
same error....

**Comment by SushantSinghRajput03** [comment]
Any Update on this

**Comment by SushantSinghRajput03** [comment]
> Edit the lines in the dart package like below and it will work. Of course the author should do this, but you can edit it yourself as well :)
> 
> **rich_suggestion.dart** Original: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.**body1!**.color)),
> 
> New: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.**bodyText1!**.color)),
> 
> **search_input.dart** Original: Icon(Icons.search, color: Theme.of(context).textTheme.**body1!**.color),
> 
> New: Icon(Icons.search, color: Theme.of(context).textTheme.**bodyText1!**.color),

**This works for me. Thanks for sharing.**

**Comment by blackmann** [comment]
Fixed in #67
