### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by hasnainelahi** [blackmann/locationpicker#68]
rich_suggestion.dart

Original: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.body1!.color)),

New: TextSpan(text: boldText, style: style.copyWith(color: Theme.of(context).textTheme.bodyText1!.color)),

search_input.dart

Original: Icon(Icons.search, color: Theme.of(context).textTheme.body1!.color),

New: Icon(Icons.search, color: Theme.of(context).textTheme.bodyText1!.color),

https://stackoverflow.com/questions/69312392/how-to-resolve-error-the-getter-body1-isnt-defined-for-the-class-texttheme

**Comment by blackmann** [comment]
Fixed with #67
