### ISSUE TITLE
Not compatible with null safety version and also with flutter 3

### ISSUE THREAD

**Issue by girishra** [blackmann/locationpicker#74]
As I'm using flutter latest version with null safety this not seem compatible with this, Please provide a latest version which compatible with flutter 3 as well as null safety. Thanks

**Comment by jtkeyva** [comment]
did you try using
[0.9.20-nullsafety](https://pub.dev/packages/place_picker/versions/0.9.20-nullsafety)

**Comment by girishra** [comment]
> did you try using [0.9.20-nullsafety](https://pub.dev/packages/place_picker/versions/0.9.20-nullsafety)

No I didn't used it because it's not mentioned in pub library, I'll try this now. Thanks
