### ISSUE TITLE
Example Code doesn't show results when entering a search

### ISSUE THREAD

**Issue by mrsqurriel** [blackmann/locationpicker#8]
I tried the example out of the box with my own google maps api key and there were no results when I typed anything into the search box. I tried removing the location and radius restrictions as well but still no results came up. 

Just wondering if there was an issue this. 

I'm using the latest version and am on the latest stable version of flutter.

**Comment by blackmann** [comment]
@xchristobear you need to enable Places API and Maps SDK for Android and iOS for your API key in your cloud console

**Comment by mrsqurriel** [comment]
Thanks. I forgot to enable one of them
